language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g npm@latest
  - npm install

script:
  - npm test

ssh_known_hosts:
  - chatbot.universdudev.ovh

after_success:
  - eval "$(ssh-agent -s)"
  - mkdir ~/.ssh
  - mv .travis-config ~/.ssh/config
  - mv .deploy.pem ~/.ssh/deploy.pem
  - chmod 600 ~/.ssh/deploy.pem
  - git remote add deploy ssh://pi@chatbot.universdudev.ovh/home/pi/chatBotBotKit/chatBotWithBotKit.git/
  - git push deploy master

before_install:
  - openssl aes-256-cbc -K $encrypted_d3a1e9dbde14_key -iv $encrypted_d3a1e9dbde14_iv -in .deploy.pem.enc -out .deploy.pem -d